name: "dev-in-docker templating"
version: "0.1.0"
description: "this template will bootstrap a base structure for your project"
delimiters: ["{{", "}}"]
variables:
  dockerfile:
    confirm: false
    variables:
      languageDeps:
        required: false
  dockerCompose:
    confirm: false
    variables:
      volumes:
        required: false
  dotbashrc:
    confirm: false
    variables:
      content:
        required: false
  runMeFirst:
    confirm: false
    variables:
      content:
        required: false
  spacemacs:
    confirm: false
    required: true
    variables:
      conflayers:
        required: true
        default: ""
      addpackages:
        required: true
        default: ""
      funcs:
        required: true
        default: ""
      confinit:
        required: true
        default: ""
      confuser:
        required: true
        default: ""
