name: "dev-in-deocker templating"
version: "0.1.0"
description: "this template will bootstrap a base structure for your project"
delimiters: ["{{", "}}"]
variables:
  dockerfile:
    confirm: false
    variables:
      languageDeps:
        required: false
  dotbashrc:
    confirm: false
    variables:
      content:
        required: false
  runMeFirst:
    confirm: false
    variables:
      content:
        required: false
  spacemacs:
    confirm: false
    variables:
      conflayers:
        required: false
      funcs:
        required: false
      confinit:
        required: false
      confuser:
        required: false
