version: '3.2'

services:
  app:
    build:
      context: .
      args:
        USER: ${USER}
        USER_ID: ${USER_ID}
    environment:
      - TERM=${TERM} # keep host's TERM, optional 
    volumes:
      - ./home:/home/${USER}:Z # Z is because of SELinux
      - ~/.ssh:/home/${USER}/.ssh:ro,Z # read-only 
