version: '3.2'

services:
  app:
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
    environment:
      - TERM=${TERM} # keep host's TERM, optional 
    volumes:
      - ./home:/home/${USER_NAME}:Z # Z is because of SELinux
      - /home/${USER_NAME}/.ssh:/home/${USER_NAME}/.ssh:ro,Z # read-only 
